### ISSUE TITLE
Some problem in Raspberry OS.

### ISSUE THREAD

**Issue by 4mod3** [entynetproject/socfish#1]
when I run `sudo sh ./install.sh`, it seems not create /root/socfish/bin.
![1~T}CH14L5R0AT 7)_D(RO](https://user-images.githubusercontent.com/35486808/68021391-3a24b680-fcdc-11e9-9dee-5e254063c257.png)

**Comment by enty8080** [comment]
What shell do you use?

**Comment by enty8080** [comment]
JUST READ THE DOCUMENTATION IN THE HOW TO INSTALL, NOT SH JUST `./install.sh`
